In [1]:
import numpy as np

In [56]:
a=np.array([[ 0.2857,  0.0178],
       [0.1428,-0.0535]])
b=np.array([3,2])

In [59]:
c=a@b

In [60]:
c

array([0.8927, 0.3214])

In [46]:
a=np.array([[3,1],[5,-8]])
a

array([[ 3,  1],
       [ 5, -8]])

In [47]:
b=np.linalg.inv(a)

b

array([[ 0.27586207,  0.03448276],
       [ 0.17241379, -0.10344828]])

In [9]:
c=np.linalg.inv(b)
c

array([[1., 2.],
       [2., 3.]])